runtime: python27
api_version: 1
threadsafe: true

handlers:
 - url: /
   static_files: build/index.html
   upload: build/index.html

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\.bak$
- ^(.*/)?(?!build)/.*$
